apiVersion: v1
kind: Namespace
metadata:
  name: ai-chatbot

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-chatbot
  namespace: ai-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-chatbot
  template:
    metadata:
      labels:
        app: ai-chatbot
    spec:
      containers:
      - name: ai-chatbot
        image: us-central1-docker.pkg.dev/humanis-server/test-api/ai-api:latest
        ports:
        - containerPort: 7860
        env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: ai-chatbot-secret
              key: TOKEN

---
apiVersion: v1
kind: Service
metadata:
  name: ai-chatbot-service
  namespace: ai-chatbot
spec:
  selector:
    app: ai-chatbot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7860
  type: ClusterIP


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-chatbot-ingress
  namespace: ai-chatbot
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  defaultBackend:
    service:
      name: ai-chatbot-service
      port:
        number: 80
  rules:
  - host: ai.server05.my.id
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: ai-chatbot-service
            port:
              number: 80
