apiVersion: v1
kind: Namespace
metadata:
  name: ai-chatbot
---
apiVersion: v1
kind: Secret
metadata:
  name: ai-chatbot-secret
  namespace: ai-chatbot
type: Opaque
data:
  TOKEN: aGZfemJmeXBsWUF2cG5GRHNjR1JsQVVOQWNodG1nbFJ0bENqaw==